version: '3'
services:
  database:
    image: neo4j
    container_name: my_neo4j_container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4jPass
      NEO4J_dbms_default__database: billy
