package com.billy.operations.api.model;

public enum Regime {
    SUELDOS_Y_SALARIOS,
    ACTIVIDADES_EMPRESARIALES_Y_PROFESIONALES,
    INCORPORACION_FISCAL,
    PERSONAS_MORALES,
    ARRENDAMIENTO,
    INTERMEDIOS,
    ENAJENACION_DE_BIENES,
    CONSOLIDACION_FISCAL;

}
